#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Preprocessing
cp -r 0.org 0
runApplication cartesianMesh
runApplication checkMesh

# Initialization
runApplication smcaVofInit -checkVolume -writeFields -invert -surfaceFile CAB_XD_95VC-clean.stl

# Postprocessing
runApplication foamToVTK
#------------------------------------------------------------------------------
