image: "openfoam-v2012_ubuntu-focal:latest"

.prepare_openfoam_and_binaries:
  script:
    ##
    ## Configure the OpenFOAM environment
    ## 
    - source /opt/OpenFOAM/OpenFOAM-v2012/etc/bashrc || true

    ##
    ## Re-use user-defined OF applications from the FOAM_USER_APPBIN artifact
    ##
    - if [ ! -d "$FOAM_USER_APPBIN" ]; then mkdir -p "$FOAM_USER_APPBIN"; fi
    - cp FOAM_USER_APPBIN/* $FOAM_USER_APPBIN

    ##
    ## Re-use user-defined OF libraries from the FOAM_USER_LIBBIN artifact
    ##
    - if [ ! -d "$FOAM_USER_LIBBIN" ]; then mkdir -p "$FOAM_USER_LIBBIN"; fi
    - cp FOAM_USER_LIBBIN/* $FOAM_USER_LIBBIN


stages:
  - building
  - running
    #- visualization    // Not defined yet (TT)
    #- testing          // Not defined yet (TT)

build_debug:
  stage: building
  script:

    ##
    ## Configure the OpenFOAM environment
    ##
    - source /opt/OpenFOAM/OpenFOAM-v2012/etc/bashrc || true

    ##
    ## Build and install
    ##
    - ./install.sh Debug

build_release:
  stage: building
  script:

    ##
    ## Configure the OpenFOAM environment
    ##
    - source /opt/OpenFOAM/OpenFOAM-v2012/etc/bashrc || true

    ##
    ## Build and install
    ##
    - ./install.sh

    ##
    ## OpenFOAM stores app and library binaries outside of project folder!
    ## To re-use project apps and libraries, use FOAM_USER_* env variables.
    ## Store the app and library binary files in a local folder and forward
    ## this folder to the next job using GitLab CI artifacts. 
    ##
   
    ## 
    ## Uncomment if the project builds user-defined OF libraries. 
    ##
    - mkdir FOAM_USER_LIBBIN && cp $FOAM_USER_LIBBIN/* FOAM_USER_LIBBIN
    - mkdir FOAM_USER_APPBIN && cp $FOAM_USER_APPBIN/* FOAM_USER_APPBIN

  artifacts:
    paths:

        ##
        ## Uncomment if user-defind OF libraries are built.
        ##
        - FOAM_USER_LIBBIN/*
       
        ##
        ## Export user-defined OF applications
        ##
        - FOAM_USER_APPBIN/*

initialization_param_study:
  stage: running
  dependencies:
    - build_release
  extends: .prepare_openfoam_and_binaries
  only:
    variables:
      - $REPRODUCE_INIT_PAPER_RESULTS != null
  script: 
   
    # Run the parameter variation tests 
    - cd cases/initialization/3Dinit
    - ./create_and_run_levelset.sh
    - ./reproduce_publication_results.sh

  artifacts:
    paths:
        - cases/initialization/3Dinit/*.csv 
        - cases/initialization/3Dinit/*.pdf 
        - cases/initialization/3Dinit/*.ipynb
        - cases/initialization/3Dinit/results/*

density_ratio_param_study:
  stage: running
  dependencies:
    - build_release
  extends: .prepare_openfoam_and_binaries
  script: 
   
    # Run the parameter variation tests 
    - source cases/scripts/bashrc
    - cd cases/hydrodynamic/translatingDroplet3D
    - argo-create-parameter-study.py densityRatioInfluence.parameter -v "0,2,4,6"
    - argo-initilize-parameter-study.py densityRatioInfluence_0000 -m blockMesh -f initFields.sh
    - argo-run-study.py interIsoRhoFoam -d densityRatioInfluence_0000 -n 4
    - jupyter-nbconvert --execute --to=html test-nb.ipynb

  artifacts:
    paths:
        - cases/hydrodynamic/translatingDroplet3D/test-nb.html

#convert_notebooks:
#  stage: visualization 
#  dependencies:
#    - param_study
#  script:
#
#    ##
#    ## Configure the OpenFOAM environment
#    ##
#    - source /opt/OpenFOAM/OpenFOAM-v2012/etc/bashrc || true
#
#    ##
#    ## Process secondary data from applications in jupyter notebooks 
#    ## - Visualize errors  
#    ## - Compute convergence rates
#    ## - Write the additional convergence data
#    ##
#    - cd cases && 
#      jupyter nbconvert fvc-reconstruct-convergence.ipynb --execute --to markdown && 
#      jupyter nbconvert fvc-reconstruct-convergence.ipynb --execute --to pdf 
#
#
#  artifacts:
#    paths:
#        ##
#        ## Secondary data used by Jupyter notebooks
#        ##
#        - cases/hex2D/*.csv 
#
#        ##
#        ## Secondary data processed by Jupyter notebooks
#        ##
#        - cases/fvc-reconstruct-data/*
#
#        ##
#        ## Jupyter Notebooks in different formats  
#        ##
#        - cases/fvc-reconstruct-convergence.ipynb
#        - cases/fvc-reconstruct-convergence_files
#        - cases/fvc-reconstruct-convergence.md
#        - cases/fvc-reconstruct-convergence.pdf
#
#test_shear2D:
#  stage: testing 
#  dependencies:
#    - convert_notebooks 
#  script:
#
#    ##
#    ## Test shear2D convergence 
#    ##
#    - cd cases &&  python test_convergence.py fvc-reconstruct-data/SHEAR_2D.csv  
#
#test_hadamard-rybczynsky2D:
#  stage: testing 
#  dependencies:
#    - convert_notebooks 
#  script:
#
#    ##
#    ## Test hadamard-rybczynsky2D convergence 
#    ##
#    - cd cases &&  python test_convergence.py fvc-reconstruct-data/HADAMARD_RYBCZYNSKY_2D.csv
#
