#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ "$GEOMTRANSPORT" != "" ]; 
then

    # Build gtest
    if [ ! -d $GEOMTRANSPORT_THIRD_PARTY ]; 
    then
        mkdir -p $GEOMTRANSPORT_THIRD_PARTY
    fi

    if [ ! -d $GEOMTRANSPORT_GTEST ];
    then
        echo "Cloning Google Test..." 
        git clone https://github.com/google/googletest.git $GEOMTRANSPORT_GTEST && \
        echo "Done cloning Google Test." 
    else
        echo "Updating Google Test..." 
        cd $GEOMTRANSPORT_GTEST && \
        git pull && \
        echo "Done updating Google Test." && \
        cd - 
    fi

    if [ ! -d $GEOMTRANSPORT_GTEST_BUILD ]; 
    then
        mkdir -p $GEOMTRANSPORT_GTEST_BUILD
    fi

    cd $GEOMTRANSPORT_GTEST_BUILD && \
    cmake -DBUILD_SHARED_LIBS=ON -Dgtest_build_samples=ON -G"Unix Makefiles" \
          $GEOMTRANSPORT_GTEST_SRC && \
    make  && \
    cd $GEOMTRANSPORT && \
    echo "Done building Google Test."
    # Build lent

    echo "Building GEOMTRANSPORT..."
    if [ "$WM_PROJECT_DIR" != "" ]; 
    then
        src/Allwmake 
        applications/Allwmake
        echo "Done building Google Test."
    else
        echo "OpenFOAM is not configured properly. Source the project's etc/bashrc file." 
    fi
else
    echo "The GEOMTRANSPORT project is not configured properly. Source the project's etc/bashrc file." 
fi
