#!/usr/bin/env bash
TEMPLATECASE=unitDomain

ALGORITHM=$1
PARAMETERFILE=$2

if [ \( "$ALGORITHM" == "" \) -o \( "$PARAMETERFILE" == "" \) -o \( ! -f "$PARAMETERFILE" \) ]; 
then 
    echo Provide two arguments to this script in the following order: the algorithm name [smci, ccmi, povof] and the PyFoam parameter *file*.  
    exit 1
fi

if [ "$ALGORITHM" != "smci" ] && [ "$ALGORITHM" != "ccmi" ] && [ "$ALGORITHM" != "povof" ];
then
    echo Algorithm $ALGORITHM not known.
    echo Valid algorithms: smci, ccmi, povof
    exit 1
fi

#voFoamParameterInit $1 $2 &&
pyFoamRunParameterVariation.py --every-variant-one-case-execution \
                               --create-database \
                               --no-server-process \
                               --no-execute-solver \
                               --no-mesh-create \
                               --no-case-setup \
                               --cloned-case-postfix=$ALGORITHM \
                               $TEMPLATECASE $PARAMETERFILE &&

# Mesh all parameterized domain cases.
for case in *${2/.parameter/}*00*${ALGORITHM}
do
    cd $case  
    if [[ "$PARAMETERFILE" == *"hexDomain"* ]];
    then
        blockMesh
    elif [[ "$PARAMETERFILE" == *"tetDomain"* ]];
    then
        tetMesh
    elif [[ "$PARAMETERFILE" == *"polyDomain"* ]];
    then
        pMesh
    else
        echo Error: No mesher assigned for $PARAMETERFILE. Name must contain
        echo either hexDomain, tetDomain or polyDomain.
        exit 1
    fi
    cd ..
done
