#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# needs to be executed to obtain good features -> proper box edges
# needs only to be executed once
#surfaceFeatureEdges -angle 50 box.stl box.fms

runApplication cartesianMesh
runApplication checkMesh

#------------------------------------------------------------------------------
