#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export GEOM_VOF_INIT=${DIR%%/etc*}

export GEOM_VOF_INIT_THIRD_PARTY=$GEOM_VOF_INIT/third-party

export PATH=$GEOM_VOF_INIT/src/scripts/:$PATH
export PYTHONPATH=$GEOM_VOF_INIT/src/scripts/:$PYTHONPATH

export CXXFLAGS=$WM_CXXFLAGS

export GEOM_VOF_INIT_CPP_DIRECTIVE='-std=c++1y' 


# Third party libraries 
export GEOM_VOF_INIT_GTEST=$GEOM_VOF_INIT_THIRD_PARTY/googletest
export GEOM_VOF_INIT_GTEST_SRC=$GEOM_VOF_INIT_GTEST/googletest
export GEOM_VOF_INIT_GTEST_INCLUDE=$GEOM_VOF_INIT_GTEST_SRC/include/gtest
export GEOM_VOF_INIT_GTEST_BUILD=$GEOM_VOF_INIT_GTEST/build

export LD_LIBRARY_PATH="$GEOM_VOF_INIT_GTEST_BUILD":$LD_LIBRARY_PATH

#source $GEOM_VOF_INIT/third-party/two-phase-validation/etc/bashrc
