#!/usr/bin/env bash


PARAMETERFILE=$1

if [ \( "$PARAMETERFILE" == "" \) -o \( ! -f "$PARAMETERFILE" \) ]; 
then 
    echo Provide the name of the parameter file as argument.  
    exit 1
fi

# Run all cases of the given study
for case in *${2/.parameter/}*00*ccmi
do
    cd $case
    sbatch ../SMCI-intersect.sbatch 
    cd ..
done 
