#!/bin/bash
pvpython ./paraview-create-cylinder.py && \
    sed -i 's/Visualization Toolkit generated SLA File/cylinder/g' cylinder.stl && \
    cartesian2DMesh 

# Orient normals inward
surfaceOrient cylinder.stl "(0.5 0.5 0.0)" cylinder.stl
